//{{NO_DEPENDENCIES}}
#define IDM_ABOUTBOX					0x0010
#define IDD_ABOUTBOX					100
#define IDS_ABOUTBOX					101
#define IDD_NARATIMER_DIALOG			102
#define IDC_EDIT						103
#define IDR_MAINFRAME					128
#define IDR_WAVE1						129
#define IDR_WAVE2						130
#define IDI_PIN							131
#define IDI_UNPIN						132
#define IDI_CLOSE						133
#define IDI_CLOSE_HOVER					134
#define IDM_NEW							200
#define IDM_TIMERMODE					201
#define IDM_ALARMMODE					202
#define IDM_TOPMOST						203
#define IDM_THEMEDEFAULT				300
#define IDM_THEMEBLACK					301
#define IDM_THEMEBLUE					302
#define IDM_THEMEGREEN					303
#define IDM_THEMEORANGE					304
#define IDM_THEMEMINT					305
#define IDM_TOGGLEDIGITALWATCH			400
#define IDM_TOGGLEDATE					401
#define IDM_TOGGLETICKSOUND				402

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
